import { Database } from 'sqlite3';

export function Migrate(db: Database) {
  db.run(
    `CREATE TABLE IF NOT EXISTS CARIMBOS (ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,NOME TEXT NOT NULL, 'CNPJ/CPF' TEXT NOT NULL)`
  );
  db.run(
    `CREATE TABLE IF NOT EXISTS FAVORECIDOS (ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,NOME TEXT NOT NULL, AGENCIA TEXT NOT NULL, CONTA TEXT NOT NULL, BANCO TEXT NOT NULL)`
  );
}
